
#include <stdio.h> 
#include <string.h>
#include <conio.h> 
#include <stdlib.h> 
#include <math.h>  


void main {

/*
Euler - Problem 2
URL: https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/



int limite= 4000000;
int suma=0;
int a=1;
int b=1;

while( b < limite ){
     if (  b % 2 == 0){
         suma +=b;   
     }// fin if
 int c= a+b;
a = b;
b= c;
}//fin while
printf(“%d”, suma);



	
int limite= 4000000;
 
int suma=0;
 
int a=1;
 
int b=1;
 
int c= a+b;
 
while ( c < limite) {
 
      suma += c;
 
a = b+c;
 
b = c+a;
 
c= a+b;
 
}//fin while
 
printf(“%d”, suma);




}//main

